import {useState,type FormEvent} from "react";
import type {Invitation,InvitationInput} from "../domain/governance";
import type {MembershipRepository} from "../application/session";
import {businesses} from "../domain/businesses";
import type {RoleId,ModuleId,AccessScope} from "../domain/access";
import {useI18n,type TranslationKey} from "../i18n/i18n";
import {useInvitationText} from "../i18n/invitations";
import {useBusinessText} from "../i18n/businesses";

const modules:ModuleId[]=["dashboard","leads","pipeline","activities","prospecting","companies","reports","admin"];
export function InvitationList({invitations,repository,onRefresh,canManage}:{invitations:Invitation[];repository?:MembershipRepository;onRefresh:()=>Promise<void>;canManage:boolean}) {
 const l=useInvitationText(),b=useBusinessText(),{t,formatDateTime}=useI18n();
 const [selected,setSelected]=useState<{invite:Invitation;action:"renew"|"delete"}|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const run=async(action:"resend"|"renew"|"delete",invite:Invitation,patch?:Pick<InvitationInput,"role"|"scope"|"modules"|"companyIds">)=>{
  if(!repository?.manageInvitation){setMessage(l.failure);return;}
  setBusy(true);setMessage("");try{await repository.manageInvitation(action,invite.id,patch);await onRefresh();setSelected(null);setMessage(l.done);}catch{setMessage(`${l.failure} ${l.wait}`);}finally{setBusy(false);}
 };
 return <><p className="invitation-note">{l.deliveryHelp}</p><button className="action-button secondary" disabled={busy} onClick={async()=>{setBusy(true);try{await onRefresh();}catch{setMessage(l.failure);}finally{setBusy(false);}}}>{l.refresh}</button>{message&&<p role="status" className="invitation-note">{message}</p>}<div className="invitation-cards">{invitations.length===0&&<p>{t("admin.noInvitations")}</p>}{invitations.map(invite=><article key={invite.id}><header><strong>{invite.email}</strong><span className="member-status invited">{invite.needsCompanySelection?l.legacy:t(`audit.invitation.${invite.status}` as TranslationKey)}</span></header><div className="invitation-companies">{invite.companyIds?.map(id=>{const business=businesses.find(b=>b.id===id);return business?<span key={id}><img src={business.logo} alt={business.name}/></span>:null;})}</div><dl><div><dt>{t("admin.assignedRole")}</dt><dd>{t(`role.${invite.role}` as TranslationKey)}</dd></div><div><dt>{t("admin.dataScope")}</dt><dd>{t(invite.scope==="organization"?"admin.allOrganization":"admin.assignedRecords")}</dd></div><div><dt>{t("admin.expires")}</dt><dd>{formatDateTime(invite.expiresAt)}</dd></div><div><dt>{l.mail}</dt><dd>{l[invite.deliveryStatus??"not_sent"]}{invite.deliveryAt&&<small>{formatDateTime(invite.deliveryAt)}</small>}</dd></div></dl>{canManage&&<footer><button className="action-button secondary" disabled={busy||invite.status!=="pending"||!!invite.needsCompanySelection} onClick={()=>run("resend",invite)}>{l.resend}</button><button className="action-button secondary" disabled={busy||invite.status==="accepted"} onClick={()=>setSelected({invite,action:"renew"})}>{l.renew}</button><button className="action-button secondary danger" disabled={busy} onClick={()=>setSelected({invite,action:"delete"})}>{l.remove}</button></footer>}</article>)}</div>{selected?.action==="delete"&&<div className="modal-backdrop"><section className="governance-modal" role="dialog" aria-modal="true" aria-labelledby="delete-invitation-title"><header><h2 id="delete-invitation-title">{l.removeTitle}</h2></header><p>{selected.invite.email}</p><p>{l.removeHelp}</p>{message&&<p role="alert">{message}</p>}<footer><button className="action-button secondary" disabled={busy} onClick={()=>setSelected(null)}>{l.cancel}</button><button className="action-button danger" disabled={busy} onClick={()=>run("delete",selected.invite)}>{l.confirmDelete}</button></footer></section></div>}{selected?.action==="renew"&&<RenewInvitation key={selected.invite.id} invite={selected.invite} busy={busy} error={message} onCancel={()=>setSelected(null)} onSave={patch=>run("renew",selected.invite,patch)} labels={{l,b}}/>}</>;
}
function RenewInvitation({invite,busy,error,onCancel,onSave,labels:{l,b}}:{invite:Invitation;busy:boolean;error:string;onCancel:()=>void;onSave:(patch:Pick<InvitationInput,"role"|"scope"|"modules"|"companyIds">)=>Promise<void>;labels:{l:ReturnType<typeof useInvitationText>;b:ReturnType<typeof useBusinessText>}}){
 const {t}=useI18n();const [ids,setIds]=useState(invite.companyIds??[]),[role,setRole]=useState<RoleId>(invite.role),[scope,setScope]=useState<AccessScope>(invite.scope==="organization"?"organization":"assigned_records"),[allowed,setAllowed]=useState<ModuleId[]>(invite.modules);
 const submit=(e:FormEvent)=>{e.preventDefault();void onSave({companyIds:ids,role,scope,modules:allowed});};
 return <div className="modal-backdrop"><section className="governance-modal" role="dialog" aria-modal="true" aria-labelledby="renew-invite-title"><header><div><h2 id="renew-invite-title">{l.renewTitle}</h2><p>{l.renewHelp}</p><strong>{invite.email}</strong></div></header><form onSubmit={submit}>{error&&<p role="alert">{error}</p>}<fieldset className="access-options"><legend>{b.invite}</legend>{businesses.map(b=><label key={b.id}><input type="checkbox" checked={ids.includes(b.id)} onChange={()=>setIds(list=>list.includes(b.id)?list.filter(x=>x!==b.id):[...list,b.id])}/>{b.name}</label>)}</fieldset><label>{t("admin.assignedRole")}<select value={role} onChange={e=>{setRole(e.target.value as RoleId);if(e.target.value==="operations_admin"){setScope("organization");setAllowed(modules);}}}>{(["operations_admin","sales_manager","sales_rep","sdr","viewer"] as const).map(r=><option key={r} value={r}>{t(`role.${r}`)}</option>)}</select></label><label>{t("admin.dataScope")}<select value={scope} onChange={e=>setScope(e.target.value as AccessScope)}><option value="organization">{t("admin.allOrganization")}</option><option value="assigned_records">{t("admin.assignedRecords")}</option></select></label><fieldset className="access-options"><legend>{t("admin.allowedModules")}</legend>{modules.map(m=><label key={m}><input type="checkbox" checked={allowed.includes(m)} onChange={()=>setAllowed(list=>list.includes(m)?list.filter(x=>x!==m):[...list,m])}/>{t(`nav.${m}`)}</label>)}</fieldset><footer><button type="button" className="action-button secondary" disabled={busy} onClick={onCancel}>{l.cancel}</button><button className="action-button" disabled={busy||!ids.length||!allowed.length}>{l.renew}</button></footer></form></section></div>;
}
